version: '3'
services:
  app:
    container_name: my-react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
