version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
      POSTGRES_DB: shine-ride
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"